Update

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,15 +1,19 @@
 # zplug
-source ~/.zplug/init.zsh
+if [ -f ~/.zplug/init.zsh ]; then
+  source ~/.zplug/init.zsh
+else
+  echo "zplug is not installed. Please install it first."
+fi
 
 zplug "themes/clean", from:oh-my-zsh
 zplug "zsh-users/zsh-autosuggestions"
 zplug "zsh-users/zsh-completions"
-zplug "zsh-users/zsh-history-substring-search"
 zplug "zsh-users/zsh-syntax-highlighting"
 zplug "b4b4r07/enhancd", use:"init.sh"
 
 # Install plugins if there are plugins that have not been installed
-if ! zplug check; then
+if ! zplug check --verbose; then
+  echo "Installing missing plugins..."
   zplug install
 fi
 zplug load
@@ -17,27 +21,31 @@ zplug load
 # completion
 setopt auto_cd
 setopt auto_pushd
-setopt correct
+setopt correct_all
 zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
 
 # history
 HISTFILE=~/.zsh_history
 HISTSIZE=10000
 SAVEHIST=10000
+setopt hist_ignore_dups
+setopt hist_ignore_space
+setopt share_history
 
 # aliases
+REPO="~/Documents/repo"
 alias vi='nvim'
 alias vim='nvim'
-alias c='clear'
 alias ls='ls -G'
 alias ll='ls -alGh'
-alias repo='cd ~/Documents/repo'
-alias tic40='cd ~/Documents/repo/tic40'
-alias atc='cd ~/Documents/repo/tic40/atcoder'
-alias dotfiles='cd ~/Documents/repo/tic40/dotfiles'
-alias gcce='g++ -std=gnu++2b -O2 -Wall -Wextra -ld_classic main.cpp && ./a.out'
-alias gccac='g++ -std=gnu++2b -O2 -Wall -Wextra -ld_classic -I /Users/tic40/Documents/repo/tic40/atcoder/libraries/ac-library main.cpp'
-alias gccace='g++ -std=gnu++2b -O2 -Wall -Wextra -ld_classic -I /Users/tic40/Documents/repo/tic40/atcoder/libraries/ac-library main.cpp && ./a.out'
+alias repo="cd ${REPO}"
+alias tic40="cd ${REPO}/tic40"
+alias atc="cd ${REPO}/tic40/atcoder"
+alias dotfiles="cd ${REPO}/tic40/dotfiles"
+alias gcce="g++ -std=gnu++2b -O2 -Wall -Wextra -ld_classic main.cpp && ./a.out"
+alias gccac="g++ -std=gnu++2b -O2 -Wall -Wextra -ld_classic -I ${REPO}/tic40/atcoder/libraries/ac-library main.cpp"
+alias gccace="g++ -std=gnu++2b -O2 -Wall -Wextra -ld_classic -I ${REPO}/tic40/atcoder/libraries/ac-library main.cpp && ./a.out"
+alias runtest="${REPO}/tic40/atcoder/scripts/runTest.sh"
 
 alias untar='tar -zxvf'
 alias wget='wget -c'
